import { AppConfig, ThemePreset } from './types';
import { SEARCH_ENGINES } from './lib/searchEngines';

export { SEARCH_ENGINES };

export interface ThemePresetMeta {
  id: ThemePreset;
  category: 'official' | 'palette';
  name: string;
  nameZh: string;
  badge?: string;
  description: string;
  backgroundCss: string;
  defaultBgUrl: string;
  cardBgClass: string;
  cardBorderClass: string;
  textClass: string;
  subtextClass: string;
  accentColor: string;
  previewColors: string[];
}

export const ALL_THEMES: Record<ThemePreset, ThemePresetMeta> = {
  /* =========================================================================
     1. 原项目 LyLme Spage Nav 官方原生主题 (Official Templates)
     ========================================================================= */
  'lylme-default': {
    id: 'lylme-default',
    category: 'official',
    name: 'LyLme Default',
    nameZh: '六零原生经典',
    badge: '官方原生',
    description: 'LyLme Spage Nav 官方原生默认主题，经典海天蓝调搜索框，圆角网格卡片与分类徽标',
    backgroundCss: 'linear-gradient(135deg, #eef2f6 0%, #e0e7ff 50%, #dbeafe 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-white/90 shadow-md backdrop-blur-md',
    cardBorderClass: 'border-transparent',
    textClass: 'text-slate-800',
    subtextClass: 'text-slate-500',
    accentColor: '#2563eb',
    previewColors: ['#2563eb', '#3b82f6', '#93c5fd', '#ffffff'],
  },
  'lylme-baisu': {
    id: 'lylme-baisu',
    category: 'official',
    name: 'BaiSu Minimal',
    nameZh: '白粟极简主题',
    badge: 'BaiSu原生',
    description: '白粟团队精作前端模板，黑白极简主义留白美学，纯净高雅，无扰沉浸阅读体验',
    backgroundCss: '#f8fafc',
    defaultBgUrl: '',
    cardBgClass: 'bg-white shadow-sm hover:shadow',
    cardBorderClass: 'border-transparent',
    textClass: 'text-slate-900',
    subtextClass: 'text-slate-500',
    accentColor: '#0f172a',
    previewColors: ['#0f172a', '#475569', '#cbd5e1', '#f8fafc'],
  },
  'lylme-baisuTwo': {
    id: 'lylme-baisuTwo',
    category: 'official',
    name: 'BaiSu Two',
    nameZh: '白粟二代卡片',
    badge: 'BaiSu进阶',
    description: '白粟二代进阶卡片主题，微弧圆角拟态边框，彩色应用图标托底，紧凑排版',
    backgroundCss: 'linear-gradient(120deg, #fdfbfb 0%, #ebedee 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-white/95 shadow-sm hover:shadow-md backdrop-blur-sm',
    cardBorderClass: 'border-transparent',
    textClass: 'text-gray-800',
    subtextClass: 'text-gray-500',
    accentColor: '#6366f1',
    previewColors: ['#6366f1', '#a5b4fc', '#e0e7ff', '#ffffff'],
  },
  'lylme-page': {
    id: 'lylme-page',
    category: 'official',
    name: 'Page Profile',
    nameZh: '个人主页/发布页',
    badge: 'Page单页',
    description: 'LyLme Spage Nav 官方个人主页/发布页主题，居中站长名片与社交矩阵，单页引导流',
    backgroundCss: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-slate-800/70 shadow-lg backdrop-blur-md',
    cardBorderClass: 'border-transparent',
    textClass: 'text-slate-100',
    subtextClass: 'text-slate-400',
    accentColor: '#38bdf8',
    previewColors: ['#38bdf8', '#0284c7', '#1e293b', '#0f172a'],
  },

  /* =========================================================================
     2. LyLme-Spage-Palette 完整调色盘主题 (Palette Templates)
     ========================================================================= */
  'palette-glass': {
    id: 'palette-glass',
    category: 'palette',
    name: 'Glass Aurora',
    nameZh: '极光磨砂 (Glassmorphism)',
    badge: 'Palette主打',
    description: '亚克力高斯模糊磨砂玻璃，极光流溢，轻奢通透，光影呼吸动效',
    backgroundCss: 'radial-gradient(ellipse at 20% 20%, rgba(56, 189, 248, 0.25) 0%, transparent 50%), radial-gradient(ellipse at 80% 80%, rgba(168, 85, 247, 0.25) 0%, transparent 50%), #0b0f19',
    defaultBgUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-white/10 backdrop-blur-xl',
    cardBorderClass: 'border-transparent',
    textClass: 'text-white',
    subtextClass: 'text-white/70',
    accentColor: '#38bdf8',
    previewColors: ['#38bdf8', '#818cf8', '#c084fc', '#0b0f19'],
  },
  'palette-cyber': {
    id: 'palette-cyber',
    category: 'palette',
    name: 'Cyber Night',
    nameZh: '暗夜黑曜 (Cyber OLED)',
    badge: '纯黑护眼',
    description: '深邃纯黑 OLED 极客暗黑夜间模式，微光冷冽青蓝霓虹，极致节能护眼',
    backgroundCss: '#05070a',
    defaultBgUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-zinc-900/80 backdrop-blur-md',
    cardBorderClass: 'border-transparent',
    textClass: 'text-zinc-100',
    subtextClass: 'text-zinc-400',
    accentColor: '#06b6d4',
    previewColors: ['#06b6d4', '#3b82f6', '#10b981', '#05070a'],
  },
  'palette-morandi': {
    id: 'palette-morandi',
    category: 'palette',
    name: 'Morandi Palette',
    nameZh: '莫兰迪调色盘 (Morandi)',
    badge: '高级灰调',
    description: '高雅低饱和度温润调色盘，灰绿烟灰雾蓝，宁静致远，高级灰质感',
    backgroundCss: 'linear-gradient(135deg, #2b303a 0%, #3a404d 50%, #4c566a 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-slate-700/40 backdrop-blur-lg',
    cardBorderClass: 'border-transparent',
    textClass: 'text-slate-100',
    subtextClass: 'text-slate-400',
    accentColor: '#a7c4bc',
    previewColors: ['#a7c4bc', '#819ca9', '#6b7b8c', '#2b303a'],
  },
  'palette-sunset': {
    id: 'palette-sunset',
    category: 'palette',
    name: 'Sunset Glow',
    nameZh: '日暮霞光 (Sunset)',
    badge: '温暖暖色',
    description: '暖橙流光与暮色晚霞，金粉交织，余晖温暖，治愈温馨晚霞',
    backgroundCss: 'linear-gradient(135deg, #2e1065 0%, #701a75 50%, #9a3412 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-amber-950/30 backdrop-blur-xl',
    cardBorderClass: 'border-transparent',
    textClass: 'text-amber-50',
    subtextClass: 'text-amber-200/70',
    accentColor: '#f97316',
    previewColors: ['#f97316', '#fbbf24', '#e11d48', '#2e1065'],
  },
  'palette-emerald': {
    id: 'palette-emerald',
    category: 'palette',
    name: 'Emerald Forest',
    nameZh: '竹影微翠 (Emerald)',
    badge: '青竹森林',
    description: '青翠竹林与晨曦微风，草木润物，森林深呼吸，舒心护眼自然绿意',
    backgroundCss: 'linear-gradient(135deg, #064e3b 0%, #065f46 50%, #047857 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1511497584788-87676104235f?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-emerald-950/40 backdrop-blur-xl',
    cardBorderClass: 'border-transparent',
    textClass: 'text-emerald-50',
    subtextClass: 'text-emerald-200/70',
    accentColor: '#10b981',
    previewColors: ['#10b981', '#34d399', '#6ee7b7', '#064e3b'],
  },
  'palette-sakura': {
    id: 'palette-sakura',
    category: 'palette',
    name: 'Sakura Breeze',
    nameZh: '浅樱和风 (Sakura)',
    badge: '落樱粉调',
    description: '落樱缤纷与淡粉和风，浪漫诗意，柔光治愈，少女感轻盈配色',
    backgroundCss: 'linear-gradient(135deg, #831843 0%, #9d174d 50%, #be185d 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-rose-950/40 backdrop-blur-xl',
    cardBorderClass: 'border-transparent',
    textClass: 'text-rose-50',
    subtextClass: 'text-rose-200/70',
    accentColor: '#f472b6',
    previewColors: ['#f472b6', '#fbcfe8', '#fb7185', '#831843'],
  },
  'palette-ocean': {
    id: 'palette-ocean',
    category: 'palette',
    name: 'Deep Ocean',
    nameZh: '星瀚深海 (Ocean)',
    badge: '湛蓝浩瀚',
    description: '深海湛蓝与苍穹星芒，广袤宁静，科技深邃，理性沉稳蓝调',
    backgroundCss: 'linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #0369a1 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-slate-900/60 backdrop-blur-xl',
    cardBorderClass: 'border-transparent',
    textClass: 'text-sky-50',
    subtextClass: 'text-sky-200/70',
    accentColor: '#38bdf8',
    previewColors: ['#38bdf8', '#0284c7', '#0ea5e9', '#0f172a'],
  },
  'palette-retro': {
    id: 'palette-retro',
    category: 'palette',
    name: 'Vintage Warmth',
    nameZh: '复古暖杏 (Vintage)',
    badge: '胶片复古',
    description: '复古胶片感与羊皮纸质感暖色，岁月静好，文雅典重咖啡暖咖色',
    backgroundCss: 'linear-gradient(135deg, #451a03 0%, #78350f 50%, #92400e 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-stone-900/60 backdrop-blur-xl',
    cardBorderClass: 'border-transparent',
    textClass: 'text-amber-100',
    subtextClass: 'text-amber-300/70',
    accentColor: '#d97706',
    previewColors: ['#d97706', '#f59e0b', '#b45309', '#451a03'],
  },
  'palette-neon': {
    id: 'palette-neon',
    category: 'palette',
    name: 'Neon Synthwave',
    nameZh: '赛博霓虹 (Neon Synth)',
    badge: '霓虹夜市',
    description: '80年代经典 Synthwave 极客霓虹，洋红荧光紫与激光青蓝交相辉映',
    backgroundCss: 'linear-gradient(135deg, #180026 0%, #290038 50%, #4a0052 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-fuchsia-950/40 backdrop-blur-xl',
    cardBorderClass: 'border-transparent',
    textClass: 'text-fuchsia-50',
    subtextClass: 'text-cyan-200/80',
    accentColor: '#d946ef',
    previewColors: ['#d946ef', '#06b6d4', '#8b5cf6', '#180026'],
  },
  'palette-pure': {
    id: 'palette-pure',
    category: 'palette',
    name: 'Pure White',
    nameZh: '素雅纯白 (Pure White)',
    badge: '极简白',
    description: '极简素白留白美学，黑白分明，无干扰纯粹浏览体验',
    backgroundCss: '#fafafa',
    defaultBgUrl: '',
    cardBgClass: 'bg-white shadow-sm hover:shadow',
    cardBorderClass: 'border-transparent',
    textClass: 'text-neutral-900',
    subtextClass: 'text-neutral-500',
    accentColor: '#171717',
    previewColors: ['#171717', '#737373', '#e5e5e5', '#fafafa'],
  },
  'palette-classic': {
    id: 'palette-classic',
    category: 'palette',
    name: 'Classic Breeze',
    nameZh: '微风经典 (Classic)',
    badge: '浅色经典',
    description: '清爽明快的水蓝浅色调，轻快开阔，日常高效实用',
    backgroundCss: 'linear-gradient(135deg, #f1f5f9 0%, #e2e8f0 50%, #cbd5e1 100%)',
    defaultBgUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2560&q=80',
    cardBgClass: 'bg-white/80 backdrop-blur-md shadow-sm',
    cardBorderClass: 'border-transparent',
    textClass: 'text-slate-800',
    subtextClass: 'text-slate-500',
    accentColor: '#2563eb',
    previewColors: ['#2563eb', '#60a5fa', '#93c5fd', '#f1f5f9'],
  },
};

// Backwards compatibility alias for components importing PALETTE_THEMES
export const PALETTE_THEMES = ALL_THEMES;

export const DEFAULT_CONFIG: AppConfig = {
  version: '2.2.0',
  title: '六零导航页 - LyLme Spage Nav',
  subtitle: 'LyLme Spage Nav (Palette 完整主题版)',
  description: '简洁高效·原版主题与Palette全量集成·无服务器部署·多云实时同步',
  icp: '',
  searchEngines: SEARCH_ENGINES,
  groups: [
    {
      id: 'daily',
      name: '常用推荐',
      icon: 'Star',
      items: [
        { id: 'gh', name: 'GitHub', url: 'https://github.com', icon: 'https://github.githubassets.com/favicons/favicon.svg', description: '全球开源代码托管与协作平台', isPinned: true },
        { id: 'bl', name: '哔哩哔哩', url: 'https://bilibili.com', icon: 'https://www.bilibili.com/favicon.ico', description: '国内知名年轻人文化社区', isPinned: true },
        { id: 'yt', name: 'YouTube', url: 'https://youtube.com', icon: 'https://www.youtube.com/favicon.ico', description: '全球高画质视频分享平台', isPinned: true },
        { id: 'zh', name: '知乎', url: 'https://zhihu.com', icon: 'https://static.zhihu.com/heifetz/favicon.ico', description: '中文互联网高质量问答社区' },
        { id: 'v2', name: 'V2EX', url: 'https://www.v2ex.com', icon: 'https://www.v2ex.com/static/icon-192.png', description: '创意工作者与极客交流讨论区' },
        { id: 'wb', name: '新浪微博', url: 'https://weibo.com', icon: 'https://weibo.com/favicon.ico', description: '随时随地发现新鲜事' },
      ],
    },
    {
      id: 'ai-tools',
      name: 'AI 效率神器',
      icon: 'Sparkles',
      items: [
        { id: 'gemini', name: 'Google Gemini', url: 'https://gemini.google.com', icon: 'https://www.gstatic.com/lamda/images/favicon_v1_150160cddff7f294ce30.svg', description: 'Google 新一代超大规模多模态大模型', isPinned: true },
        { id: 'chatgpt', name: 'ChatGPT', url: 'https://chatgpt.com', icon: 'https://oaistatic-cdn.azureedge.net/chatgpt/favicon.ico', description: 'OpenAI 旗下智能对话与生成工具', isPinned: true },
        { id: 'claude', name: 'Claude AI', url: 'https://claude.ai', icon: 'https://claude.ai/favicon.ico', description: 'Anthropic 出品，代码与长文本分析专家' },
        { id: 'deepseek', name: 'DeepSeek', url: 'https://chat.deepseek.com', icon: 'https://chat.deepseek.com/favicon.svg', description: '深度求索推理与代码模型' },
        { id: 'v0', name: 'v0 by Vercel', url: 'https://v0.dev', icon: 'https://v0.dev/favicon.ico', description: 'AI 生成式 UI 设计与 React 代码' },
        { id: 'huggingface', name: 'Hugging Face', url: 'https://huggingface.co', icon: 'https://huggingface.co/front/assets/huggingface_logo-noborder.svg', description: '开源 AI 模型与数据集首选平台' },
      ],
    },
    {
      id: 'dev-tools',
      name: '开发与文档',
      icon: 'Code',
      items: [
        { id: 'mdn', name: 'MDN Web Docs', url: 'https://developer.mozilla.org', icon: 'https://developer.mozilla.org/favicon-48x48.png', description: '权威 Web 标准、JavaScript 与 CSS 文档' },
        { id: 'npm', name: 'NPM Registry', url: 'https://www.npmjs.com', icon: 'https://static-production.npmjs.com/b0f1a831b45f5702d3480e318c72445e.png', description: 'JavaScript 软件包注册中心' },
        { id: 'stackoverflow', name: 'Stack Overflow', url: 'https://stackoverflow.com', icon: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico', description: '全球开发者问答社区' },
        { id: 'cloudflare', name: 'Cloudflare', url: 'https://dash.cloudflare.com', icon: 'https://www.cloudflare.com/favicon.ico', description: '全球 CDN、边缘计算与 DNS 服务' },
        { id: 'vercel', name: 'Vercel', url: 'https://vercel.com', icon: 'https://vercel.com/favicon.ico', description: '前端云与静态网站全球部署平台' },
        { id: 'caniuse', name: 'Can I use', url: 'https://caniuse.com', icon: 'https://caniuse.com/img/favicon-128.png', description: '浏览器前端特性兼容性查询速查' },
      ],
    },
    {
      id: 'media-design',
      name: '影音与设计',
      icon: 'Palette',
      items: [
        { id: 'unsplash', name: 'Unsplash', url: 'https://unsplash.com', icon: 'https://unsplash.com/favicon.ico', description: '免费高清高质量无版权摄影图片库' },
        { id: 'figma', name: 'Figma', url: 'https://www.figma.com', icon: 'https://static.figma.com/app/icon/1/favicon.png', description: '基于云端的新一代 UI/UX 协作设计软件' },
        { id: 'dribbble', name: 'Dribbble', url: 'https://dribbble.com', icon: 'https://cdn.dribbble.com/assets/favicon-b38525134603b9513174ec887944bde2a869eb6cd414f4d640ec40ec67a3f4b2.ico', description: '全球设计师作品灵感展示社区' },
        { id: 'spotify', name: 'Spotify Web', url: 'https://open.spotify.com', icon: 'https://open.spotifycdn.com/cdn/images/favicon32.b64ecc03.png', description: '全球海量曲库流媒体在线音乐' },
        { id: 'iconify', name: 'Iconify', url: 'https://icon-sets.iconify.design', icon: 'https://icon-sets.iconify.design/favicon.ico', description: '超 10 万+ 矢量开源图标集集合' },
      ],
    },
  ],
  theme: {
    preset: 'lylme-default',
    background: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=2560&q=80',
    useBingWallpaper: false,
    bingResolution: 'UHD',
    wallpaperType: 'preset',
    wallpaperCategory: 'all',
    wallpaperBlur: 0,
    wallpaperMaskOpacity: 0.35,
    wallpaperFit: 'cover',
    wallpaperCustomUrl: '',
    wallpaperSolidColor: '#09090b',
    wallpaperGradient: '',
    isDarkMode: false,
    opacity: 0.9,
    blur: 10,
    accentColor: '#2563eb',
    cardBorderRadius: 'rounded-2xl',
    layoutMode: 'grid',
    showClock: true,
    showHitokoto: true,
    customHitokoto: '心之所向，素履以往；生如逆旅，一苇以航。',
    openInNewTab: true,
    iconSource: 'favicon_im',
  },
  sync: {
    provider: 'none',
    autoSync: true,
    syncIntervalMinutes: 5,
    gist: {
      token: '',
      gistId: '',
      filename: 'lylme_spage.json',
    },
    githubRepo: {
      token: '',
      owner: '',
      repo: '',
      branch: 'main',
      path: 'data/lylme_spage.json',
      sha: '',
    },
    webdav: {
      url: 'https://dav.jianguoyun.com/dav/',
      username: '',
      password: '',
      filename: 'lylme_spage.json',
    },
    cfKv: {
      accountId: '',
      namespaceId: '',
      apiToken: '',
      keyName: 'lylme_spage_config',
      workerProxyUrl: '',
    },
    cfD1: {
      accountId: '',
      databaseId: '',
      apiToken: '',
      tableName: 'lylme_spage_sync',
      workerProxyUrl: '',
    },
    customApi: {
      url: '',
      method: 'PUT',
      headerKey: 'Authorization',
      headerValue: '',
    },
    lastStatus: 'idle',
  },
};
